mosip-packet-creator/pom.xml
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/CertificateController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/CommandsController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/PartnerManagerController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/PolicyManagerController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/SchemaManagerController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/CertificateService.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/CommandsService.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/PartnerService.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/PolicyManagerService.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/SchemaManagerService.java
mosipTestDataProvider/src/main/resource/config/default.properties
mosipTestDataProvider/src/main/resource/config/masterdata.properties
mosipTestDataProvider/src/org/mosip/dataprovider/preparation/MosipMasterData.java
mosipTestDataProvider/src/org/mosip/dataprovider/preparation/PolicyManagement.java
mosipTestDataProvider/src/org/mosip/dataprovider/test/partnerManagement/CertificateGenerator.java
mosipTestDataProvider/src/org/mosip/dataprovider/test/partnerManagement/CertificateUploader.java
mosipTestDataProvider/src/org/mosip/dataprovider/test/partnerManagement/PartnerRequest.java
mosipTestDataProvider/src/org/mosip/dataprovider/util/CommonUtil.java
mosipTestDataProvider/src/org/mosip/dataprovider/util/RestClient.java

1)schemamanagement
2)policymanagement
3)certificate generation(deprecated version working, current version has bugs)
4)certificate management
5)partner management(partially)

added changes from summer intership upto jul28

---

README.md
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/controller/PartnerManagerController.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/dto/Policy.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/dto/PolicyCreateDto.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/dto/SelfRegisterDto.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/dto/policyAllowedAuthType.java
mosip-packet-creator/src/main/java/io/mosip/test/packetcreator/mosippacketcreator/service/PartnerService.java
mosip-packet-creator/src/main/resources/application.properties
mosipTestDataProvider/src/org/mosip/dataprovider/test/partnerManagement/PartnerRequest.java
mosipTestDataProvider/src/variables/VariableManager.java
packet-utility-setup-linux.md
packet-utility-vscode.md

-  [x] Finished TestRig for PartnerManager Service.

Summer Internship: Completed Partner Manager, Added instructions for setting up locally

---

mosip-acceptance-tests/ivv-orchestrator/pom.xml
mosip-acceptance-tests/ivv-parser/src/main/java/io/mosip/ivv/parser/Parser.java

Updated the jacksondata bind dependency to support keyclaok user creation

---

mosipTestDataProvider/pom.xml

We updated test data provider pom to debug the mockmds cache issue along with anusha

updated pom

---

mosip-acceptance-tests/ivv-orchestrator/pom.xml

Updated pom version as 1.2.0.1-SNAPSHOT for kernel-biometrics-util

Update pom.xml for orchestrator

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/GenerateAndUploadPacketSkippingPrereg.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/GenerateAndUploadPacketSkippingPreregWithInvalidCbeff.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/UploadPacketWithInvalidHash.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/TestDataController.java

Added new scenario(Negative Flow) -- Packet is uploaded with invalid machine

MOSIP-31590

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/PacketTemplateProvider.java

Added 2 new scenarios for regproc bug verification:
- Applicant document missing in packet
- individualBiometric parameter missing in ID json

MOSIP-31048

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/GetPingHealth.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/ReadPreReq.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/WritePreReq.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/testngFile/testng.xml

TestNg report clean-up:
- Cleanup of the steps to log proper details about the step
- Restructured the logic to dump the step action in the report

MOSIP-33167

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/EmailableReport.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java

- Fix for the scenarios failures  post changes to dump step details in testNg report
- Did some report cleanup changes

MOSIP-33390

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/LoopWindow.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/BaseTestCaseUtil.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

1.  Enhance test rig where a set of steps repeated for given number of iteration count
2.  New Scenario: To check Biodeduplication stage against lost packet

MOSIP-31055

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/BaseTestCaseUtil.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/EmailableReport.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java

Optimised code in packet utility , where we are zip and encrypting the packet in order to avoid ambiguity  during parallel run.

MOSIP-33573

---

mosip-acceptance-tests/ivv-core/pom.xml
mosip-acceptance-tests/ivv-dg/pom.xml
mosip-acceptance-tests/ivv-orchestrator/pom.xml
mosip-acceptance-tests/ivv-parser/pom.xml
mosip-acceptance-tests/pom.xml
mosip-packet-creator/pom.xml
mosipTestDataProvider/pom.xml
pom.xml

Updated the POM version with respect to the module wise testrig

MOSIP-32632 Updated the POM version with respect to the module wise testrig

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/OidcClient.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java
mosipTestDataProvider/pom.xml

- New scenario (Packet creation date is null)
- Updated the mock mds version in pom.xml to "1.2.0.2"

MOSIP-32116

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/MultiFactorAuthentication.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/UpdateDemoOrBioDetails.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/Kernel.properties
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/dto/UpdatePersonaDto.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/BiometricDataProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/ResidentDataProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/mds/MDSClient.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/test/registrationclient/RegistrationSteps.java

- Fix for the existing Update flow for biometrics
- Enhancement for new Update flow scenarios
- New scenario addition -5

MOSIP-34512

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/ContextController.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/PersonaController.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/TestDataController.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/ResidentService.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/ZipUtils.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/NameProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/PacketTemplateProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/models/ResidentModel.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/preparation/MosipMasterData.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/test/CreatePersona.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/util/CommonUtil.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/util/Translator.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/variables/VariableManager.java

Reverted optimization changes for local testing

MOSIP-36029--Reverted optimization changes for local testing

---

mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/CommandsController.java

Fixed Failure at  e2e_corruptPacket getting Unable to Corrupt Packet while running scenario 48

MOSIP-37959

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/EkycOtp.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/idaData/EkycOtp/EkycOtp.yml

MOSIP-37102-Fixed failure at ekyc otp

---

mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

**1. No Biometric Match Found for the RID in Bio Dedupe Stage**
Steps to Reproduce:
- Create a New RID1 with Profile1, then upload the packet and generate UIN1.
- Create an Update Biometric RID2 for UIN1 using Profile1, then upload the packet.
**2. One Unique RID Match Found at Bio Dedupe Stage**
The UIN of the duplicate match is the same as the UIN of the update packet.
Steps to Reproduce:
- Create a New Adult RID1 with Profile1, then upload the packet and generate Adult UIN1.
- Create a New Adult RID2 with Profile2 (mark Fingerprints and Iris as exceptions), then upload the packet and generate Adult UIN2.
- Create an Update Biometric RID3 for UIN2 using Profile1, then upload the packet.

MOSIP-38404-added 2 new sceanrio for update

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/OidcClient.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/UserInfo.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/TestRunner.java

Change the import masterdata to esignet

MOSIP-37102

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/BioAuthentication.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/idaData/BioAuth/BioAuthNegative.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/idaData/BioAuth/bioAuthResultNegative.hbs

Additional scenarios with different modalities with and without exceptions and authentication behaviour

MOSIP-40370--Added 4 new scaenario 

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/User.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/GlobalConstants.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/TestRunner.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

Fixed Generate Auth Certificate Fails Due to Missing User in Key-cloak
Fixed Scenario 38 which is unable to generate private key

MOSIP-40948-Added user creation for DSL

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/CreateAndUploadExternalPacket.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SyncExternalPacket.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/dslConfigManager.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/dsl.properties
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/test-orchestrator_mz.properties
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/PacketController.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/dto/ExternalPacketRequestDTO.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/PacketTemplateProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/preparation/MosipDataSetup.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/preparation/MosipMasterData.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/util/RestClient.java

Using packet creator  it will take persona as input
In side server implementation it will  take the persona and generte packet and upload ..  and returns RID
Using that RID we can check whether UIN Is generated

MOSIP-40950- Created new Crvs scenario for extenal intergrations

---

mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/CryptoUtil.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java

encoded encryptedHash  same as packet manager code both should be same

MOSIP-41128- encoded encryptedHash  same as packet manager code

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketMakerService.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java

- Resident walk-ins to registration center completes the process and gets UIN card and generates Perpetual VID. Later updates name with VID and perform biometric authentiction with name both using UIN and VID
- Resident walk-ins to registration center completes the process  without signature and try to gets UIN card
- Resident walk-ins to registration center completes the  process  with invalid signature and try to gets UIN card

MOSIP-41275 added 3 new DSL scaenrio

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SwitchContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java

Full - it will run full suite - no need to change config map just trigger full suite it will run all scenarios
Smoke - it will run only positive scenario
sanity - it will run only default scenario 2 if want to run other scenario than 2 then you need to change config map

MOSIP-41300--Add three default RUN sanity smoke and FULL run 

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/CreateAndUploadExternalPacket.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/SetContext.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/User.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/restcall/GetWithParam.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/restcall/SimplePost.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/MachineHelper.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/UserHelper.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/dslConfigManager.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/CreatePublicKey/CreatePublicKey.hbs
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/CreatePublicKey/CreatePublicKey.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/Machine/CreateMachine.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/UpdateUserCenterMappingStatus/UpdateUserCenterMappingStatus.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/UserCenterMapping/UserCenterMapping.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/ZoneUser/CreateZoneUser.yml
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/ivv_masterdata/ZoneUser/UpdateZoneUser.yml
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/PacketController.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/dto/ExternalPacketRequestDTO.java
mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/PacketTemplateProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/util/RestClient.java

**CRVS Death Flow Enhancements**
1. Developed and integrated a new Death Flow in CRVS for lifecycle coverage.
2. Added 7 new scenarios in CRVS External Packet flow, enhancing test coverage.🔢 Updated Total Scenarios in DSL: 204

MOSIP-40950--- Added CRVS Birth scenarios 

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/CheckMultipleRidStatus.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/CheckTags.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/CredentialRequest.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/DeactivateUIN.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/DeleteHoliday.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/EsignetAuthentication.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/GenerateVID.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/GenerateVIDWithoutOTP.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/HolidayDeclaration.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/OAuthDetailsRequest.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/OidcClient.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/e2e/methods/UserInfo.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/PacketUtility.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

If signature is in valid packet should be re register

MOSIP-41520-

---

mosip-packet-creator/entrypoint.sh

Added Vm argument in entrypoint.sh file to run packet creator jar

MOSIP-41753- Added Vm argument in entrypoint.sh file to run packet creator jar

---

mosip-packet-creator/entrypoint.sh

This reverts commit 2b3655fffc4e1990f512e2297df0eadb20a45f23, reversing changes made to b9e4d4c773dd50bbdd0b18035b363ba53c2fb16c.

Revert "Merge pull request #760 from jayesh12234/patch-7"

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/EmailableReport.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/GlobalConstants.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java

added skip part in TestNg report

MOSIP-42383-added skip part in TestNg report 

---

mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java

make upload document method  thread safe

MOSIP-42375 - make upload document method  thread safe

---

mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/service/PacketSyncService.java

make upload document method thread safe

MOSIP-42375-make upload document method thread safe

---

mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

Fixed packet Integrity check failed

MOSIP-42626- Fixed packet Integrity check failed

---

mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/test/prereg/PreRegistrationSteps.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/util/RestClient.java

Fix pre reg update status intermediate issue

MOSIP-25639-Fix pre reg update status intermediate issue 

---

mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/ContactProvider.java

Remove scenario 145 , 156 ,158 from DSL as it's failing if we enable signature validation

MOSIP-42672-Remove scenario 145 , 156 ,158 from DSL as it's failing if we enable signature validation

---

mosip-acceptance-tests/ivv-core/pom.xml
mosip-acceptance-tests/ivv-dg/pom.xml
mosip-acceptance-tests/ivv-orchestrator/pom.xml
mosip-acceptance-tests/ivv-parser/pom.xml
mosip-acceptance-tests/pom.xml
mosip-packet-creator/pom.xml
mosipTestDataProvider/pom.xml
pom.xml

MOSIP-42273-Update dsl branch for java11

---

mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/scenarios.json

MOSIP-42594-Remove credential request before performing bio authentication check for child and minor

MOSIP-42594-Remove credential request before performing bio authentication check for child and minor

---

mosip-acceptance-tests/ivv-orchestrator/entrypoint.sh
mosip-packet-creator/entrypoint.sh

optimize packet creator Execution Time

optimize packet creator Execution Time

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/BaseTestCaseUtil.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/Orchestrator.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/dslConfigManager.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/BiometricDataProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/PhotoProvider.java
mosipTestDataProvider/src/io/mosip/testrig/dslrig/dataprovider/mds/MDSClient.java

added a config to run single scenario multiple times

MOSIP-43238-added a config to run single scenario multiple times

---

mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/TestRunner.java
mosip-acceptance-tests/ivv-orchestrator/src/main/java/io/mosip/testrig/dslrig/ivv/orchestrator/dslConfigManager.java
mosip-acceptance-tests/ivv-orchestrator/src/main/resources/config/dsl.properties

MOSIP-33993- ConfigMap cleanup on rancher
